nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']  # Allow any origin
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        allow_headers: ['*']  # Allow all headers
        expose_headers: ['*']  # Expose all headers
        max_age: 3600
    paths:
        '^/': null 